# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laserapp', '0010_auto_20170718_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Name of author', max_length=30, verbose_name='Author name')),
                ('date', models.CharField(max_length=30, verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laserapp.Laserapp')),
            ],
        ),
    ]
