# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
