# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laserapp', '0003_auto_20170711_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='laserapp',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laserapp',
            name='desc',
            field=models.TextField(help_text='Short description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='laserapp',
            name='name',
            field=models.CharField(help_text='Name of your material', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='laserapp',
            name='price',
            field=models.FloatField(help_text='Price of cutting', verbose_name='Price'),
        ),
    ]
