# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laserapp', '0005_auto_20170713_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='IIBook',
            fields=[
                ('ibook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laserapp.IBook')),
                ('sensor', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('laserapp.ibook',),
        ),
    ]
