# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laserapp', '0006_iibook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laserapp',
            options={},
        ),
    ]
