# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laserapp', '0007_auto_20170713_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laserapp',
            options={'verbose_name': 'Laser cutting software', 'verbose_name_plural': 'Laser cutting softwares'},
        ),
    ]
