# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laserapp', '0010_auto_20170718_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laserapp',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
